name: Test Workflow
on:
  push:
    branches-ignore:
      - release-*
    tags-ignore:
      - release-*
      - prerelease-*
  pull_request: {}
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify